name: Deploy to DonDominio

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4
            
        - name: Deploy 🚀
          uses: SamKirkland/FTP-Deploy-Action@v4.3.5
          with:
            server: ftp.annaescribano.cat
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            local-dir: ./
            server-dir: ./
            exclude:
                .git/**
                .github/**
                .gitignore